/**
 * Storefront copy, ported from the approved redesign (Arabic first, English
 * secondary). Product facts that the design mocked up (stats, partner logos,
 * payment methods) are replaced here by what the platform really does; see
 * FEATURES.md for the status of each feature.
 */
export const STOREFRONT_COPY = {
  ar: {
    brand: 'يوصل',
    langBtn: 'EN',
    account: 'حسابي',
    signIn: 'تسجيل الدخول',
    navHome: 'الرئيسية',
    navCatalog: 'كل الخدمات',
    navRequest: 'طلب خاص',
    navProviders: 'انضم كمزوّد',
    navOrders: 'طلباتي',
    navChat: 'المحادثات',
    menu: 'القائمة',
    allRegions: 'كل المناطق',
    changeRegion: 'تغيير المنطقة',

    heroKicker: 'منصة حجز خدمات المناسبات في السعودية',
    heroTitle: 'كل اللي تحتاجه مناسبتك',
    heroHighlight: 'يوصلك في مكان واحد',
    heroSub:
      'ضيافة وقهوة، قاعات، تصوير، ديكور وزفة — من مورّدين موثّقين، بسعر نهائي شامل الضريبة، وحجز إلكتروني آمن عبر ميسر.',
    searchPh: 'ابحث عن ضيافة، قاعة، كراسي…',
    searchBtn: 'ابحث',
    quick: 'الأكثر بحثاً:',
    tag1: 'ضيافة',
    tag2: 'تصوير',
    tag3: 'قاعات',
    tagInstant: 'حجز فوري',
    vatBadgeTop: '15%',
    vatBadgeBottom: 'شامل الضريبة',
    statListings: 'خدمة ومنتج',
    statCategories: 'فئة توريد',
    statRegions: 'منطقة سعودية',

    secCatsKicker: 'الأقسام',
    secCats: 'تصفّح حسب اللي تحتاجه',
    viewAll: 'عرض الكل',
    listingWord: 'خدمة',
    listingsWord: 'خدمة',
    secOccKicker: 'المناسبات',
    secOcc: 'عندك مناسبة؟ خلّها توصل',
    secTrendKicker: 'الأكثر حجزاً',
    secTrend: 'ترند هالأسبوع',
    tickerBooked: 'حُجز هالأسبوع',
    trendingBadge: 'ترند هالأسبوع',
    trendNew: 'جديد هالأسبوع',
    trendBookings: { one: 'حجز واحد هالأسبوع', two: 'حجزان هالأسبوع', few: '{n} حجوزات هالأسبوع', many: '{n} حجز هالأسبوع' },
    trendViews: { one: 'مشاهدة واحدة هالأسبوع', two: 'مشاهدتان هالأسبوع', few: '{n} مشاهدات هالأسبوع', many: '{n} مشاهدة هالأسبوع' },
    availableNow: 'متاح الآن',
    from: 'يبدأ من',
    sar: 'ر.س',
    noRatingYet: 'بدون تقييم بعد',
    secHowKicker: 'ليش يوصل؟',
    secHow: 'من أول فكرة إلى آخر ضيف',
    secHowSub: 'سواء حفلة صغيرة أو فعالية كبيرة، نمشي معك خطوة بخطوة — بدون ما تدور بين عشرات الحسابات.',
    step1T: 'اختر خدمتك',
    step1B: 'تصفّح وقارن الأسعار والتقييمات وصور الأعمال السابقة بكل شفافية.',
    step2T: 'احجز بدقايق',
    step2B: 'اختر التاريخ والكمية وادفع بأمان عبر ميسر — بلا مفاوضات ولا رسوم مخفية.',
    step3T: 'وخلّك مرتاح',
    step3B: 'مورّد موثّق يوصل في وقته، ودعمنا معك قبل وأثناء وبعد المناسبة.',
    ctaBadge: 'طلب خاص',
    ctaTitle: 'ما لقيت اللي تبيه؟',
    ctaSub: 'قل لنا وش تحتاج، وفريق يوصل يطابقه لك مع مورّد يغطي مدينتك.',
    ctaBtn: 'ابدأ طلبك',
    secRevKicker: 'آراء العملاء',
    secRev: 'عملاء سعيدين، مناسبات أسعد',
    revCountWord: 'تقييم موثّق',
    secTrust: 'موضع ثقة أبرز الجهات والعلامات',
    appTitle: 'حمّل تطبيق يوصل',
    appSub: 'تجربة أسرع على الجوال، متابعة لطلباتك، ومراسلة المورّدين من مكان واحد.',
    appInstall: 'أضف يوصل للشاشة الرئيسية',
    appScreenshot: 'تطبيق يوصل',
    footTag: 'نغيّر طريقة حجز المناسبات. بدل البحث بين عشرات الحسابات، تلقى كل خدمات مناسبتك في مكان واحد.',
    footBrowse: 'تصفّح',
    footCompany: 'الشركة',
    footCities: 'المناطق',
    footAbout: 'من نحن',
    footContact: 'تواصل معنا',
    footRefund: 'سياسة الاسترجاع',
    footSupport: 'الدعم',
    copyright: '© {year} يوصل لخدمات المناسبات',
    terms: 'الشروط والأحكام',
    privacy: 'سياسة الخصوصية',

    catTitle: 'كل الخدمات',
    catCount: 'خدمة ومنتج',
    catIn: 'في',
    filters: 'الفلاتر',
    sort: 'الترتيب',
    sortPopular: 'الأكثر طلباً',
    sortRating: 'الأعلى تقييماً',
    sortPriceAsc: 'السعر: من الأقل',
    sortPriceDesc: 'السعر: من الأعلى',
    reset: 'إعادة ضبط',
    fCity: 'المدينة',
    fPrice: 'السعر',
    fAudience: 'الجمهور',
    fLane: 'مسار التوريد',
    fRating: 'التقييم',
    noResults: 'لا توجد نتائج في هذا القسم',
    noResultsSub: 'جرّب توسيع نطاق البحث أو مسح الفلاتر، أو اترك طلبك وبنجهّز لك مورّداً مناسباً.',
    emptyMarket: 'ما فيه منتج في السوق بعد',
    emptyMarketSub:
      'السوق يعرض منتجات المورّدين المعتمدين فقط — ما نعرض صوراً ولا أسعاراً وهمية. اترك طلبك وبنوصلك أول ما يتوفر مورّد في منطقتك.',
    clearFilters: 'مسح كل الفلاتر',
    loadMore: 'عرض المزيد',
    showing: 'عرض {shown} من {total}',
    catalogError: 'تعذر تحميل كتالوج المورّدين',
    catalogErrorSub: 'حدّث الصفحة أو تواصل مع الدعم إن استمر الانقطاع.',
    retry: 'إعادة المحاولة',
    all: 'الكل',
    mostBooked: 'الأكثر طلباً',
    newBadge: 'جديد',

    verified: 'مزوّد موثّق',
    pendingVendor: 'مورّد على يوصل',
    reviewsWord: 'تقييم',
    pIncludes: 'وش يشمل الحجز',
    pCoverage: 'المدن المغطاة',
    pReviews: 'التقييمات',
    date: 'التاريخ',
    time: 'الوقت',
    qty: 'الكمية',
    total: 'الإجمالي',
    book: 'احجز الآن',
    requestBook: 'اطلب الحجز',
    addCart: 'أضف للسلة',
    added: 'تمت الإضافة للسلة',
    goToCart: 'اذهب للسلة',
    freeCancel: 'إلغاء مجاني قبل 7 أيام من الموعد',
    refundTiers: 'سياسة الاسترجاع',
    refund100: 'قبل 7 أيام',
    refund50: 'من 3 إلى 7 أيام',
    refund0: 'أقل من 3 أيام',
    related: 'قد يعجبك أيضاً',
    minNotice: 'الطلب قبل',
    perUnit: 'لكل',
    bookingModeInstant: 'حجز فوري — يتأكد مباشرة',
    bookingModeApproval: 'بموافقة المورّد — يبدأ «بانتظار موافقة المورّد»',
    vatIncluded: 'شامل الضريبة 15% · سعر نهائي',
    productMissing: 'ما لقينا هذا المنتج',
    productMissingSub: 'إما المورّد أوقفه أو الرابط غلط. تصفّح باقي الخدمات.',
    vendorPage: 'صفحة المورّد',
    noPhoto: 'بدون صورة من المورّد',

    cartTitle: 'سلة الحجز',
    cartEmpty: 'سلتك فاضية',
    cartEmptySub: 'تصفّح الخدمات وأضف اللي يناسب مناسبتك.',
    browse: 'تصفّح الخدمات',
    subtotal: 'المجموع',
    vat: 'ضريبة القيمة المضافة 15% (مشمولة)',
    checkout: 'إتمام الحجز',
    continueShop: 'متابعة التصفح',
    items: 'خدمة',
    remove: 'حذف',
    secure: 'دفع آمن ومشفّر عبر ميسر',
    unit: 'الوحدة',

    coTitle: 'إتمام الحجز',
    step1: 'بيانات المناسبة',
    step2: 'الدفع',
    step3: 'التأكيد',
    fName: 'الاسم الكامل',
    fPhone: 'رقم الجوال',
    fAddress: 'مدينة المناسبة',
    fDate: 'تاريخ المناسبة',
    fNotes: 'ملاحظات للمورّد (اختياري)',
    next: 'التالي',
    back: 'رجوع',
    payTitle: 'طريقة الدفع',
    paySub: 'الدفع يتم على صفحة ميسر الآمنة. بيانات البطاقة ما توصل يوصل.',
    payMada: 'مدى',
    payApple: 'Apple Pay',
    payCard: 'بطاقة ائتمانية',
    payStc: 'STC Pay',
    placeOrder: 'تأكيد والدفع',
    placing: 'جارٍ تثبيت الطلب…',
    coErrName: 'اكتب الاسم وجوال سعودي صحيح (05xxxxxxxx) لتأكيد الطلب والدفع.',
    coErrDate: 'اختر تاريخ المناسبة.',
    coErrNet: 'تعذر الاتصال بالخادم. حاول مرة أخرى.',
    coErrPayUrl: 'رابط الدفع من ميسر غير صالح. لم نفتح أي رابط خارج ميسر.',
    coApproval: 'طلبك يشمل منتجاً بموافقة المورّد — الطلب يبدأ «بانتظار موافقة المورّد» لين يقبله.',
    coInstant: 'كل المنتجات حجز فوري — طلبك يتأكد مباشرة بعد الدفع.',
    doneTitle: 'تم تأكيد حجزك',
    doneSub: 'ميسر أكّد الدفع. تقدر تتابع حالة الطلب من «طلباتي»، والمورّد يتواصل معك قبل المناسبة.',
    doneAmount: 'المبلغ المدفوع',
    orderNo: 'رقم الطلب',
    trackOrder: 'تابع طلبك',
    backHome: 'الرئيسية',
    payChecking: 'نتحقق من الدفع مع ميسر…',
    payFailedTitle: 'ما اكتمل الدفع',
    payFailedSub: 'العملية ما اكتملت. تقدر تعيد المحاولة من السلة.',
    payCancelledTitle: 'أُلغيت العملية',
    payCancelledSub: 'ما خصمنا شيئاً. تقدر ترجع للسلة وتدفع إلكترونياً متى ما جاهز.',
    payNoId: 'ما وصل رقم العملية من ميسر.',
    backToCart: 'الرجوع للسلة',

    ordersTitle: 'طلباتي',
    active: 'الحالية',
    past: 'السابقة',
    status0: 'قيد التأكيد',
    status1: 'مؤكد',
    status2: 'قيد التنفيذ',
    status3: 'مكتمل',
    paid: 'مدفوع',
    unpaid: 'غير مدفوع',
    resumePay: 'إكمال الدفع',
    cancelOrder: 'إلغاء الطلب',
    confirmCancel: 'تأكيد الإلغاء',
    undo: 'تراجع',
    details: 'التفاصيل',
    reorder: 'أعد الحجز',
    chatVendor: 'راسل المورّد',
    ordersEmpty: 'لا توجد طلبات هنا بعد',
    ordersEmptySub: 'أول ما تحجز خدمة تظهر هنا مع حالتها والدفع.',
    ordersGuest: 'سجّل دخولك لتشوف طلباتك',
    ordersGuestSub: 'الطلبات مرتبطة بحسابك: البريد أو الجوال اللي حجزت فيه.',
    ordersError: 'تعذر تحميل الطلبات',
    cancelNote: 'إلغاء هذا الطلب الآن:',
    refundPreviewUnpaid: 'الطلب غير مدفوع، فلا يوجد مبلغ للاسترجاع.',
    refundPreviewZero: 'حسب سياسة الاسترجاع لا يُسترجع أي مبلغ لهذا الموعد.',
    refundPreview: 'حسب سياسة الاسترجاع يُسترجع {percent}٪ من المبلغ المدفوع عبر ميسر.',
    cancelled: 'أُلغي الطلب {id}.',
    cancelledRefund: 'أُلغي الطلب {id}. يُسترجع {amount} عبر ميسر خلال 3 إلى 10 أيام عمل.',
    cancelFailed: 'تعذر إلغاء الطلب. حاول مرة أخرى.',
    eventOn: 'المناسبة',
    orderItems: 'عناصر الطلب',
    orderCity: 'المدينة',

    accTitle: 'حسابي',
    member: 'عضو في يوصل',
    edit: 'تعديل',
    mAddresses: 'عناويني',
    mPayments: 'طرق الدفع',
    mFav: 'المفضلة',
    mLang: 'اللغة',
    mSupport: 'الدعم',
    mLogout: 'تسجيل الخروج',
    mOrders: 'طلباتي',
    mChats: 'المحادثات',
    mDashboard: 'لوحة التحكم',
    mCrew: 'بوابة الطاقم',
    mVoice: 'الوكيل الصوتي',
    mVerify: 'تأكيد البريد الإلكتروني',
    mRegion: 'منطقتي',
    tileOrders: 'طلباتي',
    tileChats: 'رسائل غير مقروءة',
    tileFav: 'المفضلة',
    favEmpty: 'ما أضفت شيئاً للمفضلة بعد',
    favEmptySub: 'اضغط القلب على أي منتج ليظهر هنا.',
    accGuestTitle: 'سجّل دخولك إلى يوصل',
    accGuestSub: 'تابع طلباتك، راسل المورّدين، واحفظ المفضلة.',
    accGuestBtn: 'تسجيل الدخول أو إنشاء حساب',
    emailUnverified: 'البريد غير مؤكد',

    loginTitle: 'أهلاً بك في يوصل',
    loginSub: 'أدخل بريدك وجوالك ورقمك السري، أو أنشئ حساب عميل جديد.',
    orGuest: 'أو تابع كضيف',

    reqTitle: 'طلب خاص',
    reqSub: 'احكِ لنا عن مناسبتك، وفريق يوصل يطابق طلبك مع مورّد يغطي مدينتك ويتواصل معك.',
    rName: 'الاسم',
    rPhone: 'الجوال',
    rCity: 'المدينة / المحافظة / القرية',
    rOcc: 'نوع المناسبة',
    rDate: 'التاريخ',
    rGuests: 'عدد الضيوف',
    rBudget: 'الميزانية التقريبية',
    rDesc: 'وش تتخيل؟',
    rDescPh: 'مثال: حفلة تخرج لـ 80 شخص، ثيم أزرق، بوفيه عشاء وركن قهوة…',
    rSend: 'أرسل الطلب',
    rSending: 'جارٍ الإرسال…',
    rDoneTitle: 'وصل طلبك لإدارة يوصل',
    rDoneSub: 'بنتواصل معك على جوالك للمطابقة مع مورّد مناسب.',
    rAnother: 'طلب آخر',
    rHow: 'كيف تمشي؟',
    rH1: 'ترسل الطلب',
    rH1s: 'بالتفاصيل اللي تعرفها الآن.',
    rH2: 'نطابق المورّد',
    rH2s: 'فريق يوصل يرشّح مورّداً يغطي مدينتك.',
    rH3: 'تتواصل وتحجز',
    rH3s: 'سعر واحد واضح، ودفع آمن عبر ميسر.',
    rErr: 'تعذر إرسال الطلب',
    rErrNet: 'تعذر الاتصال بالخادم',
    guestsUnder: 'أقل من 50',
    guestsOver: 'أكثر من 500',

    prTitle: 'وسّع نشاطك مع يوصل',
    prSub: 'انضم كمورّد معتمد، اعرض منتجاتك في 15 فئة لعملاء في 13 منطقة، واستقبل حجوزات مدفوعة عبر ميسر.',
    prCta: 'سجّل كمزوّد',
    prB1: 'طلبات مدفوعة',
    prB1s: 'العميل يدفع كامل المبلغ عبر ميسر قبل ما يوصلك الطلب.',
    prB2: 'لوحة تحكم',
    prB2s: 'منتجاتك، تقويمك، مخزونك، وحجوزاتك من مكان واحد.',
    prB3: 'مكتب واتساب',
    prB3s: 'قوالب جاهزة للتأكيد والتذكير والمتابعة مع عملائك.',
    prB4: 'اعتماد من يوصل',
    prB4s: 'تراجع الإدارة ملفك قبل ظهورك في السوق.',
    prStats1: 'فئة توريد',
    prStats2: 'منطقة سعودية',
    prStats3: 'مسارات توصيل',
    prHowTitle: 'التسجيل في 3 خطوات',
    prS1: 'الهوية والمشروع',
    prS2: 'البنك والحسابات',
    prS3: 'أول منتج',

    chatTitle: 'المحادثات',
    chatSearch: 'ابحث في المحادثات',
    chatPh: 'اكتب رسالتك…',
    chatOrder: 'بخصوص الطلب',
    askVendor: 'اسأل المورّد',
    unreadWord: 'غير مقروءة',
    chatGuest: 'سجّل دخولك لتراسل المورّدين',
    chatGuestSub: 'المحادثات مرتبطة بحساب العميل. سجّل الدخول أو أنشئ حساباً.',
    chatNotClient: 'المحادثات هنا للعملاء',
    chatNotClientSub: 'بصفتك مورّداً تلقى مكتب المحادثات داخل لوحة التحكم.',

    compare: 'قارن',
    compareTitle: 'قارن بين خدمتين',
    compareSub: 'اختر خدمتين من الكتالوج لمقارنة السعر، التقييم، التغطية، وطريقة التأكيد.',
    compareEmpty: 'اختر خدمتين للمقارنة',
    compareEmptySub: 'من أي بطاقة في الكتالوج اضغط أيقونة الميزان لإضافتها هنا.',
    bestValue: 'الأفضل قيمة',
    swapItem: 'تغيير',
    cmpPrice: 'السعر',
    cmpLead: 'مهلة الحجز',
    cmpMin: 'الحد الأدنى',
    cmpCoverage: 'المدن المغطاة',
    cmpLanes: 'مسارات التوريد',
    cmpMode: 'طريقة التأكيد',
    cmpCancel: 'الإلغاء',
    cmpVerified: 'مزوّد موثّق',
    yes: 'نعم',
    no: 'لا',
    cmpRemove: 'إزالة من المقارنة',
    cmpAddHint: 'أضف خدمة ثانية',
    cmpCities: 'مدينة',

    tabHome: 'الرئيسية',
    tabCatalog: 'الخدمات',
    tabCart: 'السلة',
    tabOrders: 'طلباتي',
    tabAccount: 'حسابي',
    whatsapp: 'تواصل مع الدعم عبر واتساب',
    close: 'إغلاق',
    loading: 'جارٍ التحميل…',
    notFoundTitle: 'الصفحة غير موجودة',
  },
  en: {
    brand: 'Usil',
    langBtn: 'ع',
    account: 'Account',
    signIn: 'Sign in',
    navHome: 'Home',
    navCatalog: 'All services',
    navRequest: 'Custom request',
    navProviders: 'Become a provider',
    navOrders: 'My orders',
    navChat: 'Messages',
    menu: 'Menu',
    allRegions: 'All regions',
    changeRegion: 'Change region',

    heroKicker: 'Event services booking platform in Saudi Arabia',
    heroTitle: 'Everything your event needs,',
    heroHighlight: 'delivered in one place',
    heroSub:
      'Hospitality and coffee, halls, photography, décor and zaffa — from verified providers, with a final VAT-inclusive price and secure payment through Moyasar.',
    searchPh: 'Search hospitality, halls, chairs…',
    searchBtn: 'Search',
    quick: 'Popular:',
    tag1: 'Hospitality',
    tag2: 'Photography',
    tag3: 'Halls',
    tagInstant: 'Instant booking',
    vatBadgeTop: '15%',
    vatBadgeBottom: 'VAT included',
    statListings: 'services & products',
    statCategories: 'categories',
    statRegions: 'Saudi regions',

    secCatsKicker: 'Categories',
    secCats: 'Browse by what you need',
    viewAll: 'View all',
    listingWord: 'listing',
    listingsWord: 'listings',
    secOccKicker: 'Occasions',
    secOcc: 'Got an occasion? Let it arrive',
    secTrendKicker: 'Most booked',
    secTrend: 'Trending this week',
    tickerBooked: 'Booked this week',
    trendingBadge: 'Trending',
    trendNew: 'New this week',
    trendBookings: { one: '1 booking this week', two: '2 bookings this week', few: '{n} bookings this week', many: '{n} bookings this week' },
    trendViews: { one: '1 view this week', two: '2 views this week', few: '{n} views this week', many: '{n} views this week' },
    availableNow: 'Available now',
    from: 'From',
    sar: 'SAR',
    noRatingYet: 'No rating yet',
    secHowKicker: 'Why Usil?',
    secHow: 'From the first idea to the last guest',
    secHowSub: 'Small party or large event, we walk with you step by step — no more hunting across dozens of accounts.',
    step1T: 'Pick your service',
    step1B: 'Browse and compare prices, ratings and past work with full transparency.',
    step2T: 'Book in minutes',
    step2B: 'Choose date and quantity and pay securely through Moyasar — no haggling, no hidden fees.',
    step3T: 'Then relax',
    step3B: 'A verified provider arrives on time, and support stays with you before, during and after.',
    ctaBadge: 'Custom request',
    ctaTitle: "Can't find what you need?",
    ctaSub: 'Tell us what you need and the Usil team matches it with a provider covering your city.',
    ctaBtn: 'Start your request',
    secRevKicker: 'Client reviews',
    secRev: 'Happy clients, happier events',
    revCountWord: 'verified reviews',
    secTrust: 'Trusted by leading organizations and brands',
    appTitle: 'Get the Usil app',
    appSub: 'A faster mobile experience, order tracking, and vendor messaging in one place.',
    appInstall: 'Add Usil to your home screen',
    appScreenshot: 'Usil app',
    footTag: 'Changing how events get booked. Instead of searching dozens of accounts, find every service in one place.',
    footBrowse: 'Browse',
    footCompany: 'Company',
    footCities: 'Regions',
    footAbout: 'About us',
    footContact: 'Contact',
    footRefund: 'Refund policy',
    footSupport: 'Support',
    copyright: '© {year} Usil Event Services',
    terms: 'Terms & Conditions',
    privacy: 'Privacy Policy',

    catTitle: 'All services',
    catCount: 'services and products',
    catIn: 'in',
    filters: 'Filters',
    sort: 'Sort',
    sortPopular: 'Most requested',
    sortRating: 'Top rated',
    sortPriceAsc: 'Price: low to high',
    sortPriceDesc: 'Price: high to low',
    reset: 'Reset',
    fCity: 'City',
    fPrice: 'Price',
    fAudience: 'Audience',
    fLane: 'Fulfilment lane',
    fRating: 'Rating',
    noResults: 'No results in this category',
    noResultsSub: 'Try widening the search or clearing filters, or leave a request and we will match a provider.',
    emptyMarket: 'No products in the market yet',
    emptyMarketSub:
      'The market shows approved providers only — no stock photos or placeholder prices. Leave a request and we will reach out once a provider covers your region.',
    clearFilters: 'Clear all filters',
    loadMore: 'Load more',
    showing: 'Showing {shown} of {total}',
    catalogError: 'Could not load the catalog',
    catalogErrorSub: 'Refresh the page or contact support if it keeps failing.',
    retry: 'Retry',
    all: 'All',
    mostBooked: 'Most requested',
    newBadge: 'New',

    verified: 'Verified provider',
    pendingVendor: 'Provider on Usil',
    reviewsWord: 'reviews',
    pIncludes: "What's included",
    pCoverage: 'Cities covered',
    pReviews: 'Reviews',
    date: 'Date',
    time: 'Time',
    qty: 'Quantity',
    total: 'Total',
    book: 'Book now',
    requestBook: 'Request booking',
    addCart: 'Add to cart',
    added: 'Added to cart',
    goToCart: 'Go to cart',
    freeCancel: 'Free cancellation up to 7 days before',
    refundTiers: 'Refund policy',
    refund100: '7+ days before',
    refund50: '3 to 7 days',
    refund0: 'Under 3 days',
    related: 'You may also like',
    minNotice: 'Order ahead',
    perUnit: 'per',
    bookingModeInstant: 'Instant booking — confirmed right away',
    bookingModeApproval: 'Vendor approval — starts as "awaiting vendor approval"',
    vatIncluded: 'VAT 15% included · final price',
    productMissing: 'We could not find this product',
    productMissingSub: 'The provider may have removed it, or the link is wrong. Browse the other services.',
    vendorPage: 'Provider page',
    noPhoto: 'No photo from the provider',

    cartTitle: 'Your cart',
    cartEmpty: 'Your cart is empty',
    cartEmptySub: 'Browse services and add what fits your event.',
    browse: 'Browse services',
    subtotal: 'Subtotal',
    vat: 'VAT 15% (included)',
    checkout: 'Checkout',
    continueShop: 'Continue browsing',
    items: 'items',
    remove: 'Remove',
    secure: 'Secure encrypted payment via Moyasar',
    unit: 'Unit',

    coTitle: 'Checkout',
    step1: 'Event details',
    step2: 'Payment',
    step3: 'Confirmation',
    fName: 'Full name',
    fPhone: 'Mobile number',
    fAddress: 'Event city',
    fDate: 'Event date',
    fNotes: 'Notes for the provider (optional)',
    next: 'Next',
    back: 'Back',
    payTitle: 'Payment method',
    paySub: "Payment happens on Moyasar's secure page. Card data never reaches Usil.",
    payMada: 'mada',
    payApple: 'Apple Pay',
    payCard: 'Credit card',
    payStc: 'STC Pay',
    placeOrder: 'Confirm & pay',
    placing: 'Placing your order…',
    coErrName: 'Enter your name and a valid Saudi mobile (05xxxxxxxx) to confirm and pay.',
    coErrDate: 'Choose the event date.',
    coErrNet: 'Could not reach the server. Please try again.',
    coErrPayUrl: 'The Moyasar payment link is invalid. No link outside Moyasar was opened.',
    coApproval: 'Your order includes a vendor-approval product — it starts as "awaiting vendor approval".',
    coInstant: 'All products are instant booking — your order is confirmed right after payment.',
    doneTitle: 'Booking confirmed',
    doneSub: 'Moyasar confirmed the payment. Track the order under "My orders"; the provider will contact you before the event.',
    doneAmount: 'Amount paid',
    orderNo: 'Order no.',
    trackOrder: 'Track order',
    backHome: 'Home',
    payChecking: 'Verifying the payment with Moyasar…',
    payFailedTitle: 'Payment not completed',
    payFailedSub: 'The payment did not complete. You can retry from the cart.',
    payCancelledTitle: 'Payment cancelled',
    payCancelledSub: 'Nothing was charged. Return to the cart and pay whenever you are ready.',
    payNoId: 'Moyasar did not return a payment id.',
    backToCart: 'Back to cart',

    ordersTitle: 'My orders',
    active: 'Active',
    past: 'Past',
    status0: 'Pending',
    status1: 'Confirmed',
    status2: 'In progress',
    status3: 'Completed',
    paid: 'Paid',
    unpaid: 'Unpaid',
    resumePay: 'Resume payment',
    cancelOrder: 'Cancel order',
    confirmCancel: 'Confirm cancellation',
    undo: 'Keep order',
    details: 'Details',
    reorder: 'Book again',
    chatVendor: 'Message provider',
    ordersEmpty: 'No orders here yet',
    ordersEmptySub: 'Your bookings appear here with their status and payment.',
    ordersGuest: 'Sign in to see your orders',
    ordersGuestSub: 'Orders are tied to your account: the email or mobile used at checkout.',
    ordersError: 'Could not load orders',
    cancelNote: 'Cancelling this order now:',
    refundPreviewUnpaid: 'The order is unpaid, so there is nothing to refund.',
    refundPreviewZero: 'Under the refund policy nothing is refunded for this date.',
    refundPreview: 'Under the refund policy {percent}% of the amount paid via Moyasar is refunded.',
    cancelled: 'Order {id} cancelled.',
    cancelledRefund: 'Order {id} cancelled. {amount} is refunded via Moyasar within 3 to 10 business days.',
    cancelFailed: 'Could not cancel the order. Please try again.',
    eventOn: 'Event',
    orderItems: 'Order items',
    orderCity: 'City',

    accTitle: 'My account',
    member: 'Usil member',
    edit: 'Edit',
    mAddresses: 'Addresses',
    mPayments: 'Payment methods',
    mFav: 'Favourites',
    mLang: 'Language',
    mSupport: 'Support',
    mLogout: 'Sign out',
    mOrders: 'My orders',
    mChats: 'Messages',
    mDashboard: 'Dashboard',
    mCrew: 'Crew portal',
    mVoice: 'Voice assistant',
    mVerify: 'Verify email',
    mRegion: 'My region',
    tileOrders: 'Orders',
    tileChats: 'Unread messages',
    tileFav: 'Favourites',
    favEmpty: 'Nothing in your favourites yet',
    favEmptySub: 'Tap the heart on any product to keep it here.',
    accGuestTitle: 'Sign in to Usil',
    accGuestSub: 'Track orders, message providers and keep your favourites.',
    accGuestBtn: 'Sign in or create an account',
    emailUnverified: 'Email not verified',

    loginTitle: 'Welcome to Usil',
    loginSub: 'Enter your email, mobile and password, or create a new client account.',
    orGuest: 'or continue as guest',

    reqTitle: 'Custom request',
    reqSub: 'Tell us about your occasion and the Usil team matches it with a provider covering your city.',
    rName: 'Name',
    rPhone: 'Mobile',
    rCity: 'City / governorate / village',
    rOcc: 'Occasion type',
    rDate: 'Date',
    rGuests: 'Guests',
    rBudget: 'Approximate budget',
    rDesc: 'What do you imagine?',
    rDescPh: 'e.g. Graduation party for 80, blue theme, dinner buffet and coffee corner…',
    rSend: 'Send request',
    rSending: 'Sending…',
    rDoneTitle: 'Your request reached the Usil team',
    rDoneSub: 'We will contact you on your mobile to match a suitable provider.',
    rAnother: 'Another request',
    rHow: 'How it works',
    rH1: 'Send the request',
    rH1s: 'With whatever details you know now.',
    rH2: 'We match a provider',
    rH2s: 'The Usil team shortlists a provider covering your city.',
    rH3: 'Talk and book',
    rH3s: 'One clear price, secure payment via Moyasar.',
    rErr: 'Could not send the request',
    rErrNet: 'Could not reach the server',
    guestsUnder: 'Under 50',
    guestsOver: '500+',

    prTitle: 'Grow your business with Usil',
    prSub: 'Join as an approved provider, list in 15 categories for clients across 13 regions, and receive orders paid through Moyasar.',
    prCta: 'Register as a provider',
    prB1: 'Prepaid orders',
    prB1s: 'Clients pay the full amount via Moyasar before the order reaches you.',
    prB2: 'Provider dashboard',
    prB2s: 'Your products, calendar, inventory and bookings in one place.',
    prB3: 'WhatsApp desk',
    prB3s: 'Ready templates for confirmations, reminders and follow-ups.',
    prB4: 'Approved by Usil',
    prB4s: 'The team reviews your file before you appear in the market.',
    prStats1: 'categories',
    prStats2: 'Saudi regions',
    prStats3: 'fulfilment lanes',
    prHowTitle: 'Register in 3 steps',
    prS1: 'Identity & project',
    prS2: 'Bank & socials',
    prS3: 'First product',

    chatTitle: 'Messages',
    chatSearch: 'Search conversations',
    chatPh: 'Type a message…',
    chatOrder: 'About order',
    askVendor: 'Ask the provider',
    unreadWord: 'unread',
    chatGuest: 'Sign in to message providers',
    chatGuestSub: 'Conversations belong to a client account. Sign in or create one.',
    chatNotClient: 'Messages here are for clients',
    chatNotClientSub: 'As a provider you will find the chat desk inside your dashboard.',

    compare: 'Compare',
    compareTitle: 'Compare two services',
    compareSub: 'Pick two services from the catalog to compare price, rating, coverage and confirmation mode.',
    compareEmpty: 'Pick two services to compare',
    compareEmptySub: 'Tap the scale icon on any catalog card to add it here.',
    bestValue: 'Best value',
    swapItem: 'Change',
    cmpPrice: 'Price',
    cmpLead: 'Booking lead time',
    cmpMin: 'Minimum order',
    cmpCoverage: 'Cities covered',
    cmpLanes: 'Fulfilment lanes',
    cmpMode: 'Confirmation',
    cmpCancel: 'Cancellation',
    cmpVerified: 'Verified provider',
    yes: 'Yes',
    no: 'No',
    cmpRemove: 'Remove from comparison',
    cmpAddHint: 'Add a second service',
    cmpCities: 'cities',

    tabHome: 'Home',
    tabCatalog: 'Services',
    tabCart: 'Cart',
    tabOrders: 'Orders',
    tabAccount: 'Account',
    whatsapp: 'Contact support on WhatsApp',
    close: 'Close',
    loading: 'Loading…',
    notFoundTitle: 'Page not found',
  },
} as const;

export type StorefrontLang = keyof typeof STOREFRONT_COPY;
export type StorefrontCopy = (typeof STOREFRONT_COPY)['ar'];

/** English names for the 15 real categories; Arabic comes from `data/services.ts`. */
export const CATEGORY_EN: Record<string, string> = {
  all: 'All services',
  hospitality: 'Hospitality & coffee',
  buffet: 'Buffet & food',
  decoration: 'Décor & styling',
  photography: 'Photography',
  entertainment: 'Games & entertainment',
  halls: 'Halls & lounges',
  rental: 'Chairs, tables & rentals',
  servers: 'Coffee servers',
  av: 'Sound, lighting & screens',
  tents: 'Tents & shades',
  zaffa: 'Zaffa & folk bands',
  cakes: 'Cakes & sweets',
  invitations: 'Invitations & gifts',
  parking: 'Parking & crowd management',
  condolence: 'Condolence setups',
};

export type CountForms = { one: string; two: string; few: string; many: string };

/**
 * Arabic counts take four shapes (واحد، اثنان، 3–10 جمع، 11+ مفرد); English only
 * needs one and many. `{n}` in the chosen form is replaced by the number.
 */
export function countPhrase(n: number, forms: CountForms, ar: boolean): string {
  const count = Math.max(0, Math.floor(Number(n) || 0));
  let form: keyof CountForms;
  if (ar) form = count === 1 ? 'one' : count === 2 ? 'two' : count >= 3 && count <= 10 ? 'few' : 'many';
  else form = count === 1 ? 'one' : 'many';
  return fill(forms[form], { n: count.toLocaleString('en') });
}

/** Simple `{key}` interpolation for the few templated strings. */
export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, key: string) =>
    values[key] === undefined ? `{${key}}` : String(values[key]),
  );
}
